CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  service TEXT NOT NULL,
  event_date DATE,
  location TEXT,
  budget TEXT,
  details TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS inquiries_created_at_idx ON inquiries (created_at DESC);

INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio-media', 'portfolio-media', true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS portfolio_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  storage_path TEXT NOT NULL UNIQUE,
  public_url TEXT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS portfolio_media_category_idx ON portfolio_media (category);
CREATE INDEX IF NOT EXISTS portfolio_media_created_at_idx ON portfolio_media (created_at DESC);

ALTER TABLE portfolio_media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view portfolio media" ON portfolio_media;
CREATE POLICY "Public can view portfolio media"
  ON portfolio_media FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Only authenticated users can manage portfolio media" ON portfolio_media;
CREATE POLICY "Only authenticated users can manage portfolio media"
  ON portfolio_media FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public can view portfolio files" ON storage.objects;
CREATE POLICY "Public can view portfolio files"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'portfolio-media');

DROP POLICY IF EXISTS "Only authenticated users can manage portfolio files" ON storage.objects;
CREATE POLICY "Only authenticated users can manage portfolio files"
  ON storage.objects FOR ALL
  TO authenticated
  USING (bucket_id = 'portfolio-media')
  WITH CHECK (bucket_id = 'portfolio-media');
